# Generated by Django 3.2.3 on 2021-05-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='pick_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='values',
            field=models.CharField(max_length=1000),
        ),
    ]
